export enum IpcChannel {
    App_TitleBar = 'app_titlebar',
    App_PickFile = 'app_pickfile',
    Mods_GetComments = 'mods_comments',
    Mods_GetMod = 'mods_mod',
    Mods_Search = 'mods_search',
    Mods_GetCategories = 'mods_categories',
    Game_NewsAll = 'game_news_all',
    Game_List = 'game_list',
    Game_Verify = 'game_verify',
    Game_Setup = 'game_setup',
    Game_GetProfiles = 'game_profiles',
    Game_GetProfile = 'game_profile',
    Game_CreateProfile = 'game_create_profile',
    Game_DeleteProfile = 'game_delete_profile',
    Game_StartProfile = 'game_start_profile',
    Game_Loaders = 'game_loaders',
    Window_Minimize = 'window_minimize',
    Window_Maximize = 'window_maximize',
    Window_Close = 'window_close'
}
